### PR TITLE
fix: interpolate bare numbers with units

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
### Why

Bare numbers are not supported when interpolating to units, as seen in #643 and #1049.

### What

This pull request adds units to bare numbers when interpolating. This does not change or convert between different units.

TODO:
 - [x] Recreate issues in sandbox & verify fix propagates to hooks

### Checklist

- [ ] Documentation updated
- [ ] Demo added
- [x] Ready to be merged

### CODE REVIEW

**Comment by CodyJasonBennett** [comment]
Should I point this at master instead?

**Comment by joshuaellis** [comment]
Keep at `beta` for now so we dont loose track of which is in sync, i'll probably merge beta to master and delete beta over the next couple of days, I've just been double checking the build stuff.

**Comment by joshuaellis** [comment]
Also, i've just realised what you're looking at, awesome 💯 in-fact I can hold off on 9.2.0 until this is in, that'd be cool (there's no rush, we can keep releasing betas with fixes in the meantime).

**Comment by joshuaellis** [comment]
Is this PR ready in terms of functionality? We just need to test that it fixes the sandbox issues or is there more?

**Comment by CodyJasonBennett** [comment]
Yes, but I'll have to make sure that the fix fully propagates to the hooks.

This fixes the shared interpolation helpers.

**Comment by CodyJasonBennett** [comment]
Oh no, I didn't see this was still pending.

Although it doesn't look like anything broke since being implemented, this should be confined to web.

**Comment by joshuaellis** [comment]
Why do you think it needs to be confined to `web`?

**Comment by CodyJasonBennett** [comment]
I see. I was over-scoping the PR to validate a bit more than what's needed.

**Pull request merged**
