### PR TITLE
fix(shared): resolve circular dependencies

### PR DESCRIPTION
**Pull request by khmm12**
`shared/helpers` wants entire `shared/globals` inside `isAnimatedString`, `shared/globals` wants `noop` from `shared/helper` to assign exported variable `willAdvance`.

If `shared/helpers` is executed before `shared/globals`, `willAdvance` is initialized by given value. Otherwise `willAdvance` is initialized after `noop` inside `shared/helpers` and has no defined value.

The safest way is keep `shared/helpers` pure and move `isAnimatedString` to own module.

It fixes https://github.com/pmndrs/react-spring/issues/1078

### CODE REVIEW

**Comment by aleclarson** [comment]
Do you have a git repo I can clone to test this?

**Comment by khmm12** [comment]
Hey @aleclarson 👋

Prepared a demo ;-)

https://github.com/khmm12/react-spring-circular-dependencies-issue

Reproducible on production bundle.

**Comment by khmm12** [comment]
Did rebase the branch

**Review by TheSisb — APPROVED** [review]
I was going to PR the exact same change.

**Review by louisgv — APPROVED** [review]
LGTM 👍 @khmm12 Can we get another quick rebase for this PR for @aleclarson to merge it?

**Comment by khmm12** [comment]
@louisgv Ready ;-)

**Review by hakanozkaptan — APPROVED** [review]

**Comment by joshuaellis** [comment]
Can you merge current version 9 into your branch please so we can review this properly, I think somethings gone wild with the commits. Thank you ⭐

**Review by joshuaellis — APPROVED** [review]
Sorry its taken so long, but thank you for this fix.

**Pull request merged**
