### PR TITLE
Chore/db v9 preconstruct

### PR DESCRIPTION
**Pull request by dbismut**
## Move the build process to [Preconstruct](https://preconstruct.tools)

This is a first attempt at simplifying the repo setup by using preconstruct. This might be going nowhere because of major no-gos that I'm not able to assess at this point!

### What I've done

A lot of repeating tasks including:
- remove `tsconfig.json` files
- remove `rollup.config.js` files
- properly configure `main` and `module` entries in `package.json` files
- include the `demo` package as a yarn workspace

### What seems to work
- `yarn demo:dev` launches the Vite js demo example and fetches the code directly from source without any aliasing. It works with preconstruct dev mode which is great.
- `yarn build` does build, not sure if this meets the build requirements (upon rapid inspection, the build bundles seem to be slightly larger).

### What doesn't work yet
- [x] `yarn test` fails because of typescript errors
- [x] `yarn test:ts` also fails in `targets/zdog` and `__tests__/*` files. Note that it seems like I've enlarged the scope of the test files to all files included in the root `tsconfig.json`, so maybe some of the throwing files were actually out of scope.
- [x] ~~Codesandbox fails to import `@react-spring/types`~~

### New todos since the above is done
- [x] implement changeset
- [x] solve dependancy issue
- [x] aim to a beta branch

### CODE REVIEW

**Comment by joshuaellis** [comment]
I'm sure you're still in the middle of things, but I've noticed you've accidentally committed the `.bic-cache` files.

**Comment by dbismut** [comment]
Ooops 😭

**Comment by joshuaellis** [comment]
Okay so thats resolved *yay*

However, one issue that concerns me is the use of `*` as the pkg dependancy, it causes a lot of agg if we release any Potentially breaking changes see #1414. So ideally we need some sort of script(?) to keep them all in check? 🤔 

Secondly, we need to add `changesets` to this PR.

Thirdly, I've removed eslint for now – i'll add in a separate PR.

Finally, i'm gonna merge this into a beta branch for us because I don't want it going master with such infrastructure changes.

💯

**Comment by joshuaellis** [comment]
So:

- [ ] implement changeset
- [ ] solve dependancy issue
- [ ] aim to a beta branch

**Comment by joshuaellis** [comment]
Hey @dbismut,

I'm going to merge this around midday tomorrow unless you have any additional thoughts? Luckily changesets can do the deps update that I was talking about that time keeping the package deps in sync with one another when we publish.

Also i've managed to simplify the `jest.config.js` no idea why that was over engineered.... What we can do is release 9.2.0 as a beta, check out our demos and make sure they're still fine and then merge to master to finish the change. 

Great suggestion to do this, build and release is 10000000x faster 🚀

**Review by joshuaellis — APPROVED** [review]

**Comment by dbismut** [comment]
Wow awesome @joshuaellis! I have a lot going on at work atm so I'm not sure I'll be able to test this throughly but I'll definitely have a look when I can. Mid day as in Europe mid day?

Anyway super happy this goes through! Looks like we're finally having a common ground for some repos in pmndrs!

**Comment by joshuaellis** [comment]
Yep European midday (somewhere around 1-3 CET)

**Pull request merged**
