### PR TITLE
Fixed SSR memory leak

### PR DESCRIPTION
**Pull request by gorkalaucirica**
Fixed SSR memory leak following the approach suggested by @KB1RMA in #945.

Related to #778

### CODE REVIEW

**Comment by mario-jerkovic** [comment]
@aleclarson It would be awesome if this fix could land in v8

**Review by louisgv — APPROVED** [review]
LGTM 👍

**Comment by joshuaellis** [comment]
Is this fix required for v9? If so can you move the PR to be aimed there, please? We're focussing efforts on v9.

**Comment by Anthonyzou** [comment]
SSR memory leaks seem fixed in version `9.0.0`.

**Pull request closed without merging**
