### PR TITLE
fix: recognize `className` prop to `AnimatedComponent`s

### LINKED ISSUE #2291: [bug]: `AnimatedComponent` incorrectly interprets `className` prop as `class-name` attribute
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.3

### What's Wrong?

`<animated.div className={springValue} />` only updates `className` each React render. When the `springValue` updates, then a `class-name` attribute is updated instead of `className`.

### To Reproduce

Pass a `FluidValue` `className` to an `AnimatedComponent`.

### Expected Behaviour

`className` should be updated, not `class-name`.

### Link to repo

https://codesandbox.io/p/sandbox/dawn-platform-vclx4j

### PR DESCRIPTION
**Pull request by LoganDark**
Allows the `className` prop of animated components (like `animated.div`) to be passed a `SpringValue`.

In the past, attempting to animate this prop would result in a `class-name` attribute being created on the element instead.

Fixes #2291

### Checklist

- [x] Ready to be merged

### CODE REVIEW

**Comment by joshuaellis** [comment]
Thank you for the contribution, I do ask you fill out the PR description in detail – it's historical to the project & explains lots around why you've done what you've done etc. A good blog around this can be found here :) https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/

**Comment by LoganDark** [comment]
> I do ask you fill out the PR description in detail

Sorry, I thought linking the issue would be sufficient. fixed.

**Comment by LoganDark** [comment]
@joshuaellis anything I can do to help this get merged? The description's been updated, btw.

**Comment by actionable** [comment]
> @joshuaellis anything I can do to help this get merged? The description's been updated, btw.

+1 to this

**Comment by joshuaellis** [comment]
Hey, sorry for my late repsonse (see status) couple of things:

* looks like we need to run `prettier` on the files affected
* can we add a test in `targets/web/src/animated.test.tsx`, similar to `"accepts scrollTop and scrollLeft properties"` would be perfect.

Doing that will also help me see how it works, but from your current changes, I don't see any reason this should not be merged given we address those two points :)

**Comment by LoganDark** [comment]
This should allow an animated `className` prop to actually set an element's `className` rather than just creating a new `class-name` attribute (which is what happens currently).

As for running `prettier`, I suppose I'd have to clone the repo and install dependencies for that. I wish the style check provided a diff so I could just apply that from the online editor.

I'm currently off work, so if you still need me to clone the repo and install prettier to format the code, it'll most likely be next Monday.

**Comment by LoganDark** [comment]
(did you mean to remove the GPG signature from my commits?)

**Comment by LoganDark** [comment]
oh I see what this is. it was a rebase. give me a few minutes and I can do it myself (with proper GPG signing)

**Comment by LoganDark** [comment]
there you go~

**Review by joshuaellis — APPROVED** [review]

**Comment by joshuaellis** [comment]
Can merge this once the CI passes, thank you for your contribution, truly appreciated! ⭐

**Pull request merged**
