### PR TITLE
Fix packages/types build 

### PR DESCRIPTION
**Pull request by Aslemammad**

### CODE REVIEW

**Comment by joshuaellis** [comment]
Can you explain what shx does and why were using it over a rollup?

**Comment by Aslemammad** [comment]
Check [this](https://github.com/pmndrs/jotai/blob/master/package.json#L69) out, just for shell stuff and copying.

**Comment by joshuaellis** [comment]
image

This isnt working?

**Comment by joshuaellis** [comment]
closed in favour of pmndrs/react-spring@0b833311

**Pull request closed without merging**
