### PR TITLE
Fix test suite

### LINKED ISSUE #1353: v9: Tests won't finish
## 🐛 Bug Report

I wanted to try my luck and see whether I'd be able to fix [an issue](https://github.com/pmndrs/react-spring/issues/1149) in this repo but couldn't get the environment to run.

More specifically when running `yarn test` the tests won't finish.

when running `yarn test --testPathPattern useTransition`

this is the output:

```
yarn test --testPathPattern useTransition
yarn run v1.22.10
$ jest --testPathPattern useTransition
  console.error
    This browser does not have a MessageChannel implementation, so enqueuing tasks via await act(async () => ...) will fail. Please file an issue at https://github.com/facebook/react/issues if you encounter this warning.

      at enqueueTask (src/hooks/packages/core/node_modules/@testing-library/react/dist/@testing-library/react.esm.js:43:15)
      at Object.then (src/hooks/packages/core/node_modules/@testing-library/react/dist/@testing-library/react.esm.js:51:7)

  console.error
    Warning: An update to null inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in Unknown

      at printWarning (src/hooks/packages/core/node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (src/hooks/packages/core/node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (src/hooks/packages/core/node_modules/react-dom/cjs/react-dom.development.js:23284:7)
      at dispatchAction (src/hooks/packages/core/node_modules/react-dom/cjs/react-dom.development.js:15656:9)
      at src/hooks/packages/shared/src/hooks/useForceUpdate.ts:11:7
      at payload.onResolve (src/hooks/packages/core/src/hooks/useTransition.tsx:257:11)
      at src/hooks/packages/core/src/Controller.ts:407:30


 RUNS  packages/core/src/hooks/useTransition.test.tsx
```
##

To reproduce:

- checkout v9 branch
- yarn install
- yarn test --testPathPattern useTransition

## Environment

- `react-spring` [today's fork of v9](https://github.com/danielberndt/react-spring/tree/v9)
- `macOS` 0.15.7
- `node` v14.15.4
- `yarn` 1.22.10

### PR DESCRIPTION
**Pull request by joshuaellis**
### Why

Fix the test suite.
resolves #1353 (hopefully)

### What

Rejigged the `jest.config.js`, I decided to use the great library `ts-jest` instead of `esbuild-jest`. Which helped massively. also upgraded the version for `jest`, `@testing-library/react`, `@testing-library/jest-dom`.

Also added `"esModuleInterop": true,` to the tsconfig... 

Thoughts for later: use a `tsconfig.common.json` to consolidate some settings.

### Checklist

- [ ] Ready to be merged

### CODE REVIEW

**Comment by joshuaellis** [comment]
I'm at a real stump right now, using https://github.com/nektos/act I can run the action locally but it still throws the error. I've raised an issue in Typescript since the Discord help channels did not yield any results – https://github.com/microsoft/TypeScript/issues/43373

**Comment by joshuaellis** [comment]
@creativiii, @CodyJasonBennett & @skylineproject I can merge this if you want (the tests do run locally and complete successfully) if that's helpful for you all? Or I can keep this in a branch till the CI issue is solved, let me know.

**Comment by danielberndt** [comment]
Great! Can confirm that tests are now properly running for me 👍

image

**Comment by joshuaellis** [comment]
Awesome @danielberndt, we even have coverage checks, in an ideal world I'd like them all to be 80+ so when people contribute and bump that up I'll be bumping the bar up too!

**Pull request merged**
