### PR TITLE
feat: support the ref prop to useTrail

### PR DESCRIPTION
**Pull request by 1natsu172**
Issue #838

Support the ref prop to `useTrail` like the `useTransition`.

> useTrail with useChain at my local

### CODE REVIEW

**Comment by aleclarson** [comment]
No one's really maintaining v8 anymore. Can you port this to the latest v9 canary?

See here: https://github.com/react-spring/react-spring/tree/feat/spring-class

**Comment by 1natsu172** [comment]
Really? v8 already code frozen? ❄️ 
Later I will port to the v9canary branch.

**Comment by aleclarson** [comment]
Yeah, v9 is almost 1000 commits ahead of v8 :)

**Comment by joshuaellis** [comment]
Closing in favor of #1134

**Pull request closed without merging**
