### PR TITLE
docs: make links jump to beginning of the section

### PR DESCRIPTION
**Pull request by simlmx**
### Why

Currently going through the documentation is very annoying since it always bring you back to the big header. Many people have voiced that issue in #1799 

### What

Here I change the links in the table of content to point to the *section* (they all have a url pointing to them).
Note that I only "fixed" the links in the table of content, not the inline links of the doc.

### Checklist

- [ ] Documentation updated
- [ ] Demo added
- [ ] Ready to be merged

I'm not sure this is the proper approach but it was very straightforward to add.

### CODE REVIEW

**Comment by orta** [comment]
I was just cloning the repo to make this PR, this should get merged - reading docs by having to scroll through a page of headers each time gets annoying pretty quickly

**Comment by joshuaellis** [comment]
Looking at the deployment this doesn't work as intended, i think this is because the rehype/remark plug in doesn't use hyphens so `use-chain` should actually be `usechain`.

**Comment by orta** [comment]
No worries, I'll send a new PR with fixed links 👍🏻

**Comment by joshuaellis** [comment]
closing in favour of #1867

**Pull request closed without merging**
